### PR TITLE
Meta: make fetch() reference more precise

### PR DESCRIPTION
**Pull request by annevk**
***
<a href="https://whatpr.org/streams/1258.html" title="Last updated on Feb 20, 2023, 10:30 AM UTC (15fd71b)">Preview</a> | <a href="https://whatpr.org/streams/1258/f894acd...15fd71b.html" title="Last updated on Feb 20, 2023, 10:30 AM UTC (15fd71b)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Now it's failing on "constructor operation" and that's harder to find a suitable replacement for.

@ricea @domenic @MattiasBuelens could you please sort this out?

**Comment by MattiasBuelens** [comment]
It looks like we intend to use ["constructor operation" from WebIDL](https://webidl.spec.whatwg.org/commit-snapshots/872888179a985d88a9c6a26da07e1635a17fed08/#idl-constructors), but that doesn't export a proper definition (i.e. no `<dfn export>`).

**Comment by annevk** [comment]
Tried "constructor steps" which is roughly equivalent... I guess if it's really about the signature it might not be what you want though.

**Review by MattiasBuelens — APPROVED** [review]

**Review by ricea — APPROVED** [review]
lgtm

**Pull request merged**
