### PR TITLE
Editorial: fix extra "the" in controller.error()

### PR DESCRIPTION
**Pull request by MattiasBuelens**
As it says on the tin. 😁

***
<a href="https://whatpr.org/streams/1070.html" title="Last updated on Aug 25, 2020, 8:27 AM UTC (73e47e0)">Preview</a> | <a href="https://whatpr.org/streams/1070/8652455...73e47e0.html" title="Last updated on Aug 25, 2020, 8:27 AM UTC (73e47e0)">Diff</a>

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
Hmm, looks like [the build failed](https://github.com/whatwg/streams/pull/1070/checks?check_run_id=1018761973) for something unrelated to this PR:
```
 Error running preprocessor, returned code: 2.
LINK ERROR: No 'idl' refs found for 'MessagePort'.
{{MessagePort}}
make: *** [Makefile:23: deploy] Error 22
 ✘  Did not generate, due to fatal errors
##[error]Process completed with exit code 2.
```
Did something change in the `MessagePort` IDL definition?

**Comment by ricea** [comment]
lgtm. I will try to track down the cause of the Bikeshed error.

**Comment by domenic** [comment]
We're having strange IDL linking errors across the WHATWG spec ecosystem at the moment... https://github.com/tabatkins/bikeshed/issues/1753

**Comment by ricea** [comment]
I think if I merge it now it will produce bad output, so I will wait until the IDL linking errors are fixed.

**Comment by plinss** [comment]
There was a change to the triggers for Shepherd's IDL detection that broke the HTML spec, reverted. The DB should be updated in a few minutes.

**Pull request merged**
