### PR TITLE
Convert some general tests for ws into wpt

### PR DESCRIPTION
**Pull request by tyoshino**
Partial work for #492

### CODE REVIEW

**Comment by domenic** [comment]
OK, I think I fixed wpt-runner and moved the files around enough to make the build succeed. Let me know what you think. The actual conversion LGTM.

**Comment by domenic** [comment]
We should probably merge this ASAP so that we don't write any more tests in the old format, like I did in #513.

**Comment by tyoshino** [comment]
lgtm. Thanks for adding the feature to the wpt-runner. Merging.

**Comment by tyoshino** [comment]
Merged as eb9bb0cbada0165c3fdad61825856e480f9f60f8

**Pull request closed without merging**
