### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by tomayac**
`s/Detached/detached`

***
<a href="https://whatpr.org/streams/1099.html" title="Last updated on Feb 9, 2021, 9:30 AM UTC (c192963)">Preview</a> | <a href="https://whatpr.org/streams/1099/0397808...c192963.html" title="Last updated on Feb 9, 2021, 9:30 AM UTC (c192963)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
This is not correct; it needs to be uppercase per the HTML Standard.

**Comment by tomayac** [comment]
> This is not correct; it needs to be uppercase per the HTML Standard.

Just to clarify, this is about [this](https://streams.spec.whatwg.org/#transformstream-detached:~:text=%5B%5Bwritable%5D%5D-,%5B%5BDetached%5D%5D,-A%20boolean%20flag%20set%20to%20true%20when%20the%20stream%20is%20transferred) instance for example.

Screen Shot 2021-01-06 at 16 54 35

**Comment by domenic** [comment]
Indeed. [[Detached]] must be uppercase, otherwise you can't transfer the object.

**Comment by tomayac** [comment]
> Indeed. [[Detached]] must be uppercase, otherwise you can't transfer the object.

Thanks for clarifying. In this case, just a typo fix remains.

**Comment by tomayac** [comment]
(More of a note to self, but maybe interesting for others): [`[[Detached]]`](https://html.spec.whatwg.org/multipage/structured-data.html#detached).

**Review by ricea — APPROVED** [review]
Typo fix lgtm.

**Review by ricea — CHANGES_REQUESTED** [review]
Oops, looks like you need to fix the line wrapping to get within 100 characters. Sorry!

**Review by ricea — APPROVED** [review]
Thanks!

**Pull request merged**
