### PR TITLE
Don't error an errored WritableStream on messageerror

### PR DESCRIPTION
**Pull request by ricea**
- [ ] At least two implementers are interested (and none opposed):
   * …
   * …
- [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * The change is not observable.
- [ ] [Implementation bugs](https://github.com/whatwg/meta/blob/master/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chrome: Not needed (never had the bug)
   * Firefox: Not needed (unimplemented)
   * Safari: Not needed (unimplemented)

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

***
<a href="https://whatpr.org/streams/1069.html" title="Last updated on Aug 27, 2020, 9:05 PM UTC (8c8f6dc)">Preview</a> | <a href="https://whatpr.org/streams/1069/8652455...8c8f6dc.html" title="Last updated on Aug 27, 2020, 9:05 PM UTC (8c8f6dc)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
> It appears to be impossible to test in a cross-browser fashion

Can you say more? Is this change totally unobservable?

**Comment by ricea** [comment]
Elaborating on the testing issue, I have been unable to find a cross-browser method to cause a messageerror event. RTCCertificate posted to a Worker should cause a messageerror by the standard because it is a Window-only type, but in practice in Chrome lets you send it to a Worker anyway. SharedArrayBuffer might be a viable option in future, but is not currently practical.

**Comment by domenic** [comment]
Sending a `WebAssembly.Module` to a cross-site (note: cross-origin does not suffice) page will reliably cause a `messageerror`. See https://github.com/web-platform-tests/wpt/blob/6c2b980cd5a4bb8c64eeea5c89899051bd4f4fa0/origin-isolation/resources/helpers.mjs#L214 for some examples of how to set that up in web platform tests.

**Comment by ricea** [comment]
After writing a test for this, I found it wasn't observable anyway. If an error/close occurred locally, then we won't be in a state where we can send a new chunk. If it happened remotely, then the remote side will have disentangled the message pipe already, so messageerror will never fire.

I still prefer to make this change, as the reason why it's not needed is extremely subtle.

**Pull request merged**
