### PR TITLE
Add code coverage reporting the reference implementation/tests

### PR DESCRIPTION
**Pull request by domenic**
See https://dl.dropboxusercontent.com/u/20140634/streams-spec-coverage/index.html for a preview. The gaps are interesting, although mostly minor, which is great.

### CODE REVIEW

**Comment by isonmad** [comment]
I already filed https://github.com/domenic/wpt-runner/pull/3 yesterday, since it looked like a bug in wpt-runner. Did you see that?

**Comment by domenic** [comment]
Ah, no, I got bit by the bug where sometimes on GitHub you aren't watching your own repos. Thanks for finding that.

**Comment by isonmad** [comment]
There's a bug like that? Damn. Was hoping the mention at https://github.com/whatwg/streams/pull/579#ref-issue-186588912 would get noticed if nothing else.

**Comment by domenic** [comment]
Hmm now updating wpt-runner causes a few new failures due to testharness.js updates...

**Comment by domenic** [comment]
Test failures straightened out; this should be usable now.

**Comment by ricea** [comment]
Awesome! lgtm

**Pull request merged**
