### PR TITLE
Add WritableStream.close()

### LINKED ISSUE #1007: Should there be a WritableStream.close() method?
It appears that currently the only way to close (without aborting) a writable stream is by calling `getWriter`, and then calling `close()` on that writer. Would it make sense to also expose `close()` directly on `WritableStream` itself?

Presumably you'd only be able to call such a method if the stream isn't locked (just like abort on the stream can only be called if the stream isn't locked).

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Fixes #1007

WPT PR: web-platform-tests/wpt#18693

***
<a href="https://whatpr.org/streams/1011.html" title="Last updated on Nov 3, 2019, 10:18 PM UTC (bfbf1df)">Preview</a> | <a href="https://whatpr.org/streams/1011/d26db0e...bfbf1df.html" title="Last updated on Nov 3, 2019, 10:18 PM UTC (bfbf1df)">Diff</a>

### CODE REVIEW

**Comment by ricea** [comment]
Sorry for the delay. It looks great. I haven't been able to find a single thing that needs changing.

Could you land the wpt changes first? Then I will land this.

**Comment by MattiasBuelens** [comment]
> Could you land the wpt changes first? Then I will land this.

I knew I forgot something! 😅

**Comment by MattiasBuelens** [comment]
@ricea This PR is still open, although the WPT PR has already landed and the related issue has already been closed. I suppose you simply forgot to merge this PR? 😅

**Comment by MattiasBuelens** [comment]
Oh right, [the deploy failed](https://travis-ci.org/whatwg/streams/builds/579464629). 😕

```
Running deploy for commit: 8d6c0a6f49bf1dd0fa23140cdabaf347e32eef61

Linting the source:
All good

Starting commit snapshot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  300k    0   260  100  300k     94   109k  0:00:02  0:00:02 --:--:--  109k
Error running preprocessor, returned code: 1.
LINK ERROR: No 'dfn' refs found for 'transforming' that are marked for export.
&lt;a data-link-type="dfn" data-lt="transforming">transforming&lt;/a>
 ✘  Did not generate, due to fatal errorsMakefile:10: recipe for target 'deploy' failed
make: *** [deploy] Error 22
The command "make deploy" exited with 2.
```

Is this related to #1020? Are we blocked from merging any PRs until those links are fixed?

**Comment by MattiasBuelens** [comment]
Rebased onto `master` with no conflicts. The new deploy completed successfully, should be ready to land! 🚀

**Pull request merged**
