### PR TITLE
Correct submodule

### PR DESCRIPTION
**Pull request by tyoshino**

### CODE REVIEW

**Comment by tyoshino** [comment]
https://github.com/w3c/web-platform-tests/commit/2bf671b26f3e690d7302a74adaab15934081702a is on master
https://github.com/w3c/web-platform-tests/commit/5dfffa5f98c91f22ee3d4570dd8be8b457f3c3b4 is on the branch for PR.

Fixing the submodule to point at https://github.com/w3c/web-platform-tests/commit/2bf671b26f3e690d7302a74adaab15934081702a

**Comment by tyoshino** [comment]
I created this PR just for passing the presubmit requirement `continuous-integration/travis-ci`. Could I do that without a PR?

**Comment by domenic** [comment]
I think you should be allowed to push to master even without passing any presubmit requirements? Did you get an error? I often find it useful to send a PR just to check that Travis CI agrees with me, though.

**Comment by tyoshino** [comment]
This is the log.

```
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To github.com:whatwg/streams.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:whatwg/streams.git'
```

**Comment by tyoshino** [comment]
Hmm, I might just have made some mistake?

**Comment by domenic** [comment]
No, I looked through the permissions, and it looks like only repository "admins" had access to push without hitting the presubmit check. And it turns out you only had write access, not admin. I've made you an admin :)

**Comment by tyoshino** [comment]
Ah, I see! Thanks :)

**Comment by tyoshino** [comment]
That said, it's still good that admins are also supervised by the protected branch feature. If we can run the travis-ci manually on console, it's not a burden.

Quickly skimmed the documents, e.g. https://help.github.com/articles/defining-the-mergeability-of-pull-requests/, but it seems we cannot. So, for the meantime, admins could create PRs when needed to benefit from the check.

**Pull request merged**
