### PR TITLE
Small typo in underlying sink

### PR DESCRIPTION
**Pull request by surma**
***
<a href="https://whatpr.org/streams/894.html" title="Last updated on Mar 6, 2018, 9:44 PM GMT (e69deec)">Preview</a> | <a href="https://whatpr.org/streams/894/7952128...e69deec.html" title="Last updated on Mar 6, 2018, 9:44 PM GMT (e69deec)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
Thank you!

**Comment by MattiasBuelens** [comment]
Actually, shouldn't the signature be `write(chunk, controller)` instead of just `write(chunk)`?

**Comment by ricea** [comment]
@MattiasBuelens Good catch, yes.

**Comment by surma** [comment]
Fixed in #897

**Pull request merged**
