### PR TITLE
Meta: default branch rename

### PR DESCRIPTION
**Pull request by annevk**
Helps with https://github.com/whatwg/meta/issues/174.

I did not audit the reference-implementation directory. If that is important can an editor take that on?

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
I couldn't find any references to `master` within the reference implementation directory, so I think we're fine there.

Do we also intend to change the default branch name on this repository? And should that be part of this pull request? If so, we'll need to update:
* the GitHub Actions workflows
* the `deploy.sh` script
* some links in our demos, e.g. [this one in `transform-stream-polyfill.js`](https://github.com/whatwg/streams/blob/039780837354e94c461749d3be82a2ccb16c99c1/demos/transforms/transform-stream-polyfill.js#L3)
* the link in [`wpt/streams/README.md`](https://github.com/web-platform-tests/wpt/blob/c12cdbb11af62ed7d9c60df77265cfee8d8cee71/streams/README.md) that points back to the reference implementation

**Comment by annevk** [comment]
Thanks @MattiasBuelens! `deploy.sh` is not in this repository, I could not find other links in `demos/` but I did update the one you found as well as the workflows, and created https://github.com/web-platform-tests/wpt/pull/27182 for WPT (I could not find other such references back to WHATWG repositories).

**Review by MattiasBuelens — APPROVED** [review]
Woops, right, I didn't see that `deploy.sh` from my working copy was being gitignored. 😅

LGTM. 👍

**Review by ricea — APPROVED** [review]
lgtm

**Pull request merged**
