### PR TITLE
Remove abortReason property from WritableStream spec

### PR DESCRIPTION
**Pull request by nidhijaju**
Based on https://github.com/whatwg/streams/issues/1165, this change removes the abortReason property from the WritableStream spec, as we are no longer implementing it, and will rather use the reason from the AbortSignal when that is added in the DOM spec.

@yutakahirano Does this look okay?

***
<a href="https://whatpr.org/streams/1177.html" title="Last updated on Oct 25, 2021, 5:37 PM UTC (96e5a0b)">Preview</a> | <a href="https://whatpr.org/streams/1177/ea03a24...96e5a0b.html" title="Last updated on Oct 25, 2021, 5:37 PM UTC (96e5a0b)">Diff</a>

### CODE REVIEW

**Comment by nidhijaju** [comment]
Closing and reopening to trigger the CI again as I believe the wpt PR should have fixed the check failure.

**Comment by nidhijaju** [comment]
I'm running into some test failures related to the `WritableStreamDefaultController interface`, however I think those can only be fixed by updating https://github.com/web-platform-tests/wpt/blob/master/interfaces/streams.idl. However, IIUC that file will not be generated until the spec is updated, and the spec cannot be updated until the tests pass. What should be done in this case?

**Comment by MattiasBuelens** [comment]
You're right. This is quite the chicken or the egg situation! 😅

We could *temporarily* disable the Web IDL tests by adding `idlharness.any.html` here:
https://github.com/whatwg/streams/blob/ea03a24deb75928bfa7c285611d4ac2daf332957/reference-implementation/run-web-platform-tests.js#L35-L39

Then we can land the spec change, wait for [`@webref/idl`](https://github.com/w3c/webref) and WPT to pick up the new Web IDL, and finally roll WPT in this repo and re-enable the test.

@domenic Thoughts?

**Comment by MattiasBuelens** [comment]
This is quite scary though. Any spec change that affects the Web IDL won't get tested against the reference implementation until WPT has updated their Web IDL. So proposed additions like `ReadableStream.from(asyncIterable)` or `ReadableStreamBYOBReader.fill(view)` can't be fully tested before we land them. 😕

**Comment by nidhijaju** [comment]
Thank you @domenic! I'll make the relevant WPT PR/changes on Monday. Please let me know by then if you think we should wait more.

**Pull request merged**
